[units]
power = "watt"                      # watt | mwatt
temp = "celcius"                    # celcius | fahrenheit | kelvin | rankine | r√©aumur

[style]
theme_mode = "dark"                 # dark | light
theme_light_palette = "winter"      # winter | black | nord
theme_dark_palette =  "dim"         # dracula | night | dim 
tab = "settings"                    # dashboard | profiles | settings
profile = "system"                  # system | custom | turbo | fixed